name: Publish site
on:
  push:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      pages: write 
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: sh build.sh
      - name: upload
        uses: actions/upload-pages-artifact@0252fc4ba7626f0298f0cf00902a25c6afc77fa8 # 3.0.0
        with:
          name: github-pages
          path: dist
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4.0.3
      - name: update index
        env:
          FM_USER: ${{ secrets.FM_USER }}
          FM_PASS: ${{ secrets.FM_PASS }}
        run: |
          curl -X PUT -d index.html https://myfiles.fastmail.com/selfassembled.org/index.html -u $FM_USER:$FM_PASS
